spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: ${PORT:8765}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:87651/eureka}
